### 서버 테스트
GET http://localhost:3005/

//회원가입
###
POST http://localhost:3005/auth/signup
Content-Type: application/json

{
  "email": "pck123@naver.com",
  "password": "q1w2e3r4t5",
  "nickname": "창기"
}

###
//로그인 
POST http://localhost:3005/auth/login
Content-Type: application/json

{
  "email": "pck123@naver.com",
  "password": "q1w2e3r4t5"
}

### accessToken 재발급 (자동 로그인)
POST http://localhost:3005/auth/refresh
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWo4OG8xMGkwMDAwY2V6OHJvb3BnNnFoIiwiaWF0IjoxNzY1ODcwMTE0LCJleHAiOjE3NjY0NzQ5MTR9.WJFmS4Idiy_XWbTjowbtFyOKaauNiLAt-sqEUY88sW0"
}

### 로그인한 사용자 정보 불러오기
GET http://localhost:3005/auth/me
Authorization: Bearer 

### /auth/me 오류 테스트
GET http://localhost:3005/auth/me
Authorization: Bearer 

### 로그아웃
POST http://localhost:3005/auth/logout
Authorization: Bearer 

### 갤러리 조회
GET http://localhost:3005/cards/my
Authorization: Bearer 

### 갤러리 상세조회
GET http://localhost:3005/cards/my/cmiy78kql0003c3z81obpylmc
Authorization: Bearer 